### ISSUE TITLE
Can't import Python libraries

### ISSUE THREAD

**Issue by cchoirat** [EricaMoreira/SemSeg#6]
With Slicer 4.11.0 on OSX:

![image](https://user-images.githubusercontent.com/4173925/64459739-e8efb080-d0f8-11e9-982c-5ef6a501c894.png)

```python
>>> pip_install("scipy")
Could not import runpy module
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1129, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1245, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1285, in _fill_cache
OSError: [Errno 34] Result too large: '/private/var/folders/hp/m3pc9m7n67xch87cfjg_8r480000gp/T/AppTranslocation/614F2F98-F9FC-4E95-A9F5-4271FD8BEA29/d'
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/private/var/folders/hp/m3pc9m7n67xch87cfjg_8r480000gp/T/AppTranslocation/614F2F98-F9FC-4E95-A9F5-4271FD8BEA29/d/Slicer.app/Contents/bin/Python/slicer/util.py", line 2022, in pip_install
    logProcessOutput(proc)
  File "/private/var/folders/hp/m3pc9m7n67xch87cfjg_8r480000gp/T/AppTranslocation/614F2F98-F9FC-4E95-A9F5-4271FD8BEA29/d/Slicer.app/Contents/bin/Python/slicer/util.py", line 1975, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['/private/var/folders/hp/m3pc9m7n67xch87cfjg_8r480000gp/T/AppTranslocation/614F2F98-F9FC-4E95-A9F5-4271FD8BEA29/d/Slicer.app/Contents/bin/../bin/PythonSlicer', '-m', 'pip', 'install', 'scipy']' returned non-zero exit status 1.
```

**Comment by EricaMoreira** [comment]
I suggest you delete your version of 3D Slicer and download the most recent Preview Release for Mac OS X. 

It looks like you were using revision 28482. I just downloaded and tested using revision 28485 and it works as expected:

<img width="672" alt="Screen Shot 2019-09-08 at 11 37 11 AM" src="https://user-images.githubusercontent.com/36380470/64490687-9d8aee80-d22d-11e9-9a40-43311787d031.png">
<img width="567" alt="Screen Shot 2019-09-08 at 11 36 06 AM" src="https://user-images.githubusercontent.com/36380470/64490689-a1b70c00-d22d-11e9-84a6-0a3949f3ec6b.png">

**Comment by EricaMoreira** [comment]
Also be sure that you are opening 3D Slicer from _inside your Applications folder_. This is because 3D Slicer needs to be opened from a writable location.
